/**
 * Canonical ingredient + brand maps. Drives community extraction (section 2),
 * delta tracking between days (section 5) and future on-site tagging.
 * Format: canonical display name -> list of lowercase aliases to match.
 */
export const INGREDIENTS = {
  'Niacinamide': ['niacinamide', 'vitamin b3', 'b3 serum'],
  'Retinol / Retinoids': ['retinol', 'retinal', 'retinaldehyde', 'retinoid', 'retinoids', 'tretinoin', 'tret', 'adapalene', 'differin', 'accutane', 'isotretinoin'],
  'Hyaluronic Acid': ['hyaluronic', 'hyaluronic acid', 'ha serum', 'sodium hyaluronate'],
  'Ceramides': ['ceramide', 'ceramides'],
  'Centella Asiatica (Cica)': ['centella', 'cica', 'madecassoside', 'asiaticoside'],
  'Azelaic Acid': ['azelaic', 'azelaic acid'],
  'Salicylic Acid (BHA)': ['salicylic', 'salicylic acid', 'bha'],
  'Glycolic / AHA': ['glycolic', 'aha', 'lactic acid', 'mandelic'],
  'Vitamin C': ['vitamin c', 'ascorbic', 'l-ascorbic', 'ascorbyl'],
  'Benzoyl Peroxide': ['benzoyl peroxide', 'bpo', 'panoxyl'],
  'Peptides': ['peptide', 'peptides', 'matrixyl', 'argireline', 'copper peptide'],
  'Snail Mucin': ['snail mucin', 'mucin', 'snail secretion'],
  'Propolis / Honey': ['propolis', 'honey extract', 'manuka'],
  'Mugwort': ['mugwort', 'artemisia'],
  'Rice Extract': ['rice extract', 'rice water', 'black rice'],
  'Ginseng': ['ginseng', 'red ginseng'],
  'PDRN / Salmon DNA': ['pdrn', 'salmon dna', 'salmon pdrn'],
  'Exosomes': ['exosome', 'exosomes'],
  'Bakuchiol': ['bakuchiol'],
  'Collagen': ['collagen', 'bio-collagen', 'biocollagen'],
  'Panthenol (B5)': ['panthenol', 'provitamin b5'],
  'Squalane': ['squalane'],
  'Tranexamic Acid': ['tranexamic', 'tranexamic acid'],
  'Kojic Acid': ['kojic', 'kojic acid'],
  'Urea': ['urea'],
  'Allantoin': ['allantoin'],
  'Mineral / Zinc SPF': ['zinc oxide', 'mineral sunscreen', 'mineral spf'],
  'Sunscreen (unspecified)': ['sunscreen', 'spf', 'sunblock', 'sun screen', 'sun protection'],
  'Micellar Water': ['micellar'],
  'Hypochlorous Acid': ['hypochlorous', 'hypochlorous acid'],
};

export const BRANDS = {
  'COSRX': ['cosrx'],
  'CeraVe': ['cerave'],
  'Anua': ['anua'],
  'Beauty of Joseon': ['beauty of joseon', 'boj'],
  'Purito Seoul': ['purito'],
  'Haruharu Wonder': ['haruharu'],
  'Skin1004': ['skin1004', 'skin 1004'],
  'Medicube': ['medicube'],
  'Round Lab': ['round lab', 'roundlab'],
  'Laneige': ['laneige'],
  'Innisfree': ['innisfree'],
  'La Roche-Posay': ['la roche-posay', 'la roche posay', 'lrp'],
  'The Ordinary': ['the ordinary'],
  "Paula's Choice": ["paula's choice", 'paulas choice'],
  'Dr. Jart+': ['dr jart', 'dr. jart'],
  'Biodance': ['biodance'],
  'Mediheal': ['mediheal'],
  'Torriden': ['torriden'],
  'Isntree': ['isntree'],
  'Mixsoon': ['mixsoon'],
  'Numbuzin': ['numbuzin'],
  'Tocobo': ['tocobo'],
  'Byoma': ['byoma'],
  'Glow Recipe': ['glow recipe'],
  'Tatcha': ['tatcha'],
  'Supergoop': ['supergoop'],
  'EltaMD': ['eltamd'],
  'Avène': ['avene', 'avène'],
  'Bioderma': ['bioderma'],
  'Eucerin': ['eucerin'],
  'Neutrogena': ['neutrogena'],
  'Olay': ['olay'],
  'Nivea': ['nivea'],
  'Aquaphor': ['aquaphor'],
  'Vaseline': ['vaseline'],
};